### ISSUE TITLE
Plazback won't work on active Subtitles

### ISSUE THREAD

**Issue by dasmaetthes** [itouch5000/plugin.video.mediathekviewweb#1]
When I activate Subtitles in Settings the playback of some Videos doesn't work. Tried it for example with ARD - Tatort

**Comment by itouch5000** [comment]
The plugin can only handle subtitles if the source (https://mediathekviewweb.de) provides them. For example `ARD - Tatort - Der Tote im Nachtzug` does not has subtitles but `ARD - Tatort - Blaues Blut` has some.
Or do you mean that the plugin produces an error and the whole video does not start? If so then please provide a debug log.
