### ISSUE TITLE
Kodi 19 support?

### ISSUE THREAD

**Issue by Isayso** [itouch5000/plugin.video.mediathekviewweb#2]
The addon does not work on Kodi 19, I think because of missing Python 3 support?

What are your future plans? 

Thanks, great tool!

**Comment by itouch5000** [comment]
Thanks for this issue. Yes I will look into this within the next days.

**Comment by itouch5000** [comment]
implemented in version 1.3.0

**Comment by Isayso** [comment]
Thank You!!!
