### ISSUE TITLE
Version for Kodi 19?

### ISSUE THREAD

**Issue by probonopd** [itouch5000/plugin.video.mediathekviewweb#7]
Hello, great plugin. Is there a version for Kodi 19, which is using Python 3?

**Comment by vbprofi** [comment]
Hello, I have updated for Kodi 19+ that plugin. you find my updated version here: https://github.com/vbprofi/kodi-19---repo/tree/main/plugin.video.mediathekviewweb

**Comment by kasi45** [comment]
https://github.com/kasi45/plugin.video.mediathekviewweb

**plugin.video.mediathekviewweb - V2**

**Comment by probonopd** [comment]
Thank you very much @kasi45, works well.
